// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlb4DDUdGpv5g4DqDXUIqusRzsMuLI5dI',
    appId: '1:879469245579:web:4c1f1ed1ada454d592108e',
    messagingSenderId: '879469245579',
    projectId: 'video-dowloader-2dfa0',
    authDomain: 'video-dowloader-2dfa0.firebaseapp.com',
    storageBucket: 'video-dowloader-2dfa0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC-szTVlH9phQx9CYuuRSfgOM-jBVyM6U',
    appId: '1:879469245579:android:ccb52e624922d42392108e',
    messagingSenderId: '879469245579',
    projectId: 'video-dowloader-2dfa0',
    storageBucket: 'video-dowloader-2dfa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-axKK8ZZjwFPRTgIDsEaheqIQxv3Eqw',
    appId: '1:879469245579:ios:d0a1ea452689d8df92108e',
    messagingSenderId: '879469245579',
    projectId: 'video-dowloader-2dfa0',
    storageBucket: 'video-dowloader-2dfa0.appspot.com',
    iosBundleId: 'com.example.videodownloader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd-axKK8ZZjwFPRTgIDsEaheqIQxv3Eqw',
    appId: '1:879469245579:ios:d47d1299b79aa9b592108e',
    messagingSenderId: '879469245579',
    projectId: 'video-dowloader-2dfa0',
    storageBucket: 'video-dowloader-2dfa0.appspot.com',
    iosBundleId: 'com.example.videodownloader.RunnerTests',
  );
}
